import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  indexSidebar: [{type: 'autogenerated', dirName: 'index'}],
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: 'tutorial'}],
  devguideSidebar: [{type: 'autogenerated', dirName: 'devguide'}],
  extguideSidebar: [{type: 'autogenerated', dirName: 'extguide'}],
  referenceSidebar: [{type: 'autogenerated', dirName: 'reference'}],
  opensourceSidebar: [{type: 'autogenerated', dirName: 'opensource'}],
  appmarketSidebar: [{type: 'autogenerated', dirName: 'appmarket'}],
  // Community sidebar for community resources
  communitySidebar: [{type: 'autogenerated', dirName: 'community'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
