name: Build and Package

on:
  workflow_dispatch: # Manual trigger

jobs:
  build-and-package:
    name: Build and Package
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      
      - name: Build project
        run: pnpm run build
      
      - name: Create package
        run: |
          tar -czf jitaidocs.tar.gz build/
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jitaidocs-${{ github.sha }}
          path: jitaidocs.tar.gz
          retention-days: 30
