name: CI Check

on:
  pull_request:
    branches: [ master ]

jobs:
  pr-build-check:
    name: PR Build Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: TypeScript type check
        run: pnpm run typecheck
      
      - name: Build project
        env:
          DOCUSAURUS_SSR_CONCURRENCY: 1
          CI: true
        run: pnpm run build
      
      - name: Comment PR result
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ All checks passed! This PR is ready to be merged.'
            })
      
      - name: Comment PR failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ Checks failed! Please fix TypeScript errors or build issues and try again.'
            })
